# Generated by Django 6.0.3 on 2026-05-01 10:17

from django.db import migrations, models


SQL_007_EDGE_GATEWAY = """
-- Edge Gateway Database Schema Migration
-- Implements the global execution surface under MARP governance

-- Edge audit table: Immutable audit log for all Edge decisions
CREATE TABLE edge_audit (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    request_id VARCHAR(36) NOT NULL,
    subsystem VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL,
    user_id VARCHAR(255),
    region_code VARCHAR(50),
    decision VARCHAR(20) NOT NULL, -- 'allow', 'block', 'quarantine'
    risk_score DECIMAL(3,2) NOT NULL,
    policy_version VARCHAR(50) NOT NULL,
    execution_time INTEGER NOT NULL, -- milliseconds
    rationale TEXT,
    quarantine_reason TEXT,
    quarantine_duration BIGINT,
    escalation_required BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Edge telemetry table: Telemetry data sent to MARP
CREATE TABLE edge_telemetry (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    request_id VARCHAR(36) NOT NULL,
    subsystem VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL,
    decision VARCHAR(20) NOT NULL,
    risk_score DECIMAL(3,2) NOT NULL,
    policy_version VARCHAR(50) NOT NULL,
    execution_time INTEGER NOT NULL,
    hash VARCHAR(64) NOT NULL,
    original_request JSONB,
    policy_snapshot_id UUID,
    region_code VARCHAR(50),
    instance_id VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Edge anomalies table: Anomalies detected and reported
CREATE TABLE edge_anomalies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    anomaly_type VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL, -- 'low', 'medium', 'high', 'critical'
    request_id VARCHAR(36),
    subsystem VARCHAR(50),
    description TEXT NOT NULL,
    context JSONB,
    reported_to_marp BOOLEAN DEFAULT false,
    marp_response JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Edge policy snapshots table: Cached policy snapshots per region
CREATE TABLE edge_policy_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subsystem VARCHAR(50) NOT NULL,
    region_code VARCHAR(50) NOT NULL,
    version VARCHAR(50) NOT NULL,
    content JSONB NOT NULL,
    hash VARCHAR(64) NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_until TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(subsystem, region_code, version)
);

-- Edge subsystem adapters registry: Tracks available adapters
CREATE TABLE edge_adapter_registry (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subsystem VARCHAR(50) UNIQUE NOT NULL,
    adapter_name VARCHAR(100) NOT NULL,
    version VARCHAR(20) NOT NULL,
    capabilities JSONB NOT NULL,
    health_status VARCHAR(20) DEFAULT 'healthy',
    last_health_check TIMESTAMPTZ DEFAULT NOW(),
    config JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Extended tables for new subsystems

-- Matchmaking events
CREATE TABLE edge_matchmaking_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    match_id VARCHAR(36) NOT NULL,
    user_ids TEXT[] NOT NULL,
    score DECIMAL(5,2) NOT NULL,
    policy_version VARCHAR(50) NOT NULL,
    region_code VARCHAR(50),
    rationale TEXT,
    anomaly_flags JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- AI Programs runs
CREATE TABLE edge_ai_program_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    program_id VARCHAR(36) NOT NULL,
    version VARCHAR(20) NOT NULL,
    context_hash VARCHAR(64) NOT NULL,
    subsystem VARCHAR(50) NOT NULL,
    allow_block_state VARCHAR(20) NOT NULL,
    execution_result JSONB,
    safety_checks JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Chatbot logs
CREATE TABLE edge_chatbot_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    prompt_hash VARCHAR(64) NOT NULL,
    response_hash VARCHAR(64) NOT NULL,
    safety_flags JSONB,
    intent_classification VARCHAR(50),
    confidence_score DECIMAL(3,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Marketing deliveries
CREATE TABLE edge_marketing_deliveries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id VARCHAR(36) NOT NULL,
    audience_id VARCHAR(36) NOT NULL,
    region_code VARCHAR(50),
    status VARCHAR(20) NOT NULL,
    consent_state BOOLEAN DEFAULT true,
    delivery_channel VARCHAR(20),
    content_hash VARCHAR(64),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Geocoding logs
CREATE TABLE edge_geocoding_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    request_id VARCHAR(36) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    query TEXT NOT NULL,
    accuracy DECIMAL(5,2),
    region_code VARCHAR(50),
    response_time INTEGER,
    cache_hit BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_edge_audit_request_id ON edge_audit(request_id);
CREATE INDEX idx_edge_audit_subsystem_decision ON edge_audit(subsystem, decision);
CREATE INDEX idx_edge_audit_created_at ON edge_audit(created_at DESC);
CREATE INDEX idx_edge_audit_user_id ON edge_audit(user_id);

CREATE INDEX idx_edge_telemetry_request_id ON edge_telemetry(request_id);
CREATE INDEX idx_edge_telemetry_subsystem ON edge_telemetry(subsystem);
CREATE INDEX idx_edge_telemetry_created_at ON edge_telemetry(created_at DESC);

CREATE INDEX idx_edge_anomalies_type_severity ON edge_anomalies(anomaly_type, severity);
CREATE INDEX idx_edge_anomalies_created_at ON edge_anomalies(created_at DESC);

CREATE INDEX idx_edge_policy_snapshots_subsystem_region ON edge_policy_snapshots(subsystem, region_code);
-- Composite index to speed up the specific query used by the Gateway for current active policies
CREATE INDEX idx_edge_policy_snapshots_active_lookup ON edge_policy_snapshots(subsystem, region_code, effective_from DESC) WHERE is_active = true;

CREATE INDEX idx_edge_adapter_registry_subsystem ON edge_adapter_registry(subsystem);
CREATE INDEX idx_edge_adapter_registry_capabilities ON edge_adapter_registry USING GIN (capabilities);

-- Extended subsystem indexes
CREATE INDEX idx_matchmaking_events_match_id ON edge_matchmaking_events(match_id);
CREATE INDEX idx_matchmaking_events_region ON edge_matchmaking_events(region_code);

CREATE INDEX idx_ai_program_runs_program_id ON edge_ai_program_runs(program_id);
CREATE INDEX idx_ai_program_runs_subsystem ON edge_ai_program_runs(subsystem);

CREATE INDEX idx_chatbot_logs_session_id ON edge_chatbot_logs(session_id);
CREATE INDEX idx_chatbot_logs_user_id ON edge_chatbot_logs(user_id);

CREATE INDEX idx_marketing_deliveries_campaign ON edge_marketing_deliveries(campaign_id);
CREATE INDEX idx_marketing_deliveries_region ON edge_marketing_deliveries(region_code);

CREATE INDEX idx_geocoding_logs_request_id ON edge_geocoding_logs(request_id);
CREATE INDEX idx_geocoding_logs_provider ON edge_geocoding_logs(provider);

-- Insert default adapter registry entries
INSERT INTO edge_adapter_registry (subsystem, adapter_name, version, capabilities) VALUES
('ecommerce', 'ecommerce-adapter', '1.0.0', '{"consent": true, "fraud": true, "compliance": true}'),
('payments', 'payments-adapter', '1.0.0', '{"reversible": true, "escrow": true, "safety": true}'),
('fraud', 'fraud-adapter', '1.0.0', '{"detection": true, "prevention": true, "monitoring": true}'),
('matchmaking', 'matchmaking-adapter', '1.0.0', '{"scoring": true, "eligibility": true, "anti-manipulation": true}'),
('ai-programs', 'ai-programs-adapter', '1.0.0', '{"execution": true, "safety": true, "monitoring": true}'),
('ai-engine-chatbot', 'chatbot-adapter', '1.0.0', '{"intent-filtering": true, "safety": true, "throttling": true}'),
('proximity-geocoding', 'geocoding-adapter', '1.0.0', '{"polygon": true, "boundary": true, "caching": true}'),
('communication', 'communication-adapter', '1.0.0', '{"consent": true, "quiet-hours": true, "throttling": true}'),
('automated-marketing(pap_v1)', 'marketing-adapter', '1.0.0', '{"consent": true, "frequency": true, "segmentation": true}'),
('places-venues', 'places-adapter', '1.0.0', '{"geofencing": true, "hours": true, "classification": true}');

-- Insert initial policy snapshot
INSERT INTO edge_policy_snapshots (
    subsystem, region_code, version, content, hash, effective_from
) VALUES (
    'global',
    'ALL',
    '1.0.0',
    '{
      "rules": [
        {
          "id": "default-deny",
          "action": "block",
          "rationale": "Default deny for unverified requests",
          "conditions": []
        }
      ],
      "riskThreshold": 0.7,
      "defaultAction": "allow"
    }'::jsonb,
    'initial_policy_hash',
    NOW()
);

-- GSO Orchestration Schema (Planetary Routing & Isolation)
-- Required for GSOService and Planetary Load Balancing

CREATE TABLE region_catalog (
    region_code VARCHAR(50) PRIMARY KEY,
    parent_region_code VARCHAR(50) REFERENCES region_catalog(region_code),
    brand_config JSONB NOT NULL DEFAULT '{}',
    locale_config JSONB NOT NULL DEFAULT '{}',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE gso_network_nodes (
    node_id VARCHAR(100) PRIMARY KEY,
    region_code VARCHAR(50) REFERENCES region_catalog(region_code),
    node_type VARCHAR(50) NOT NULL, -- 'cloud_region', 'external_network', 'satellite'
    endpoint_url TEXT NOT NULL,
    health_status VARCHAR(20) DEFAULT 'healthy',
    is_active BOOLEAN DEFAULT true,
    metadata JSONB DEFAULT '{}',
    last_seen TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE gso_routing_decisions (
    request_id VARCHAR(100) PRIMARY KEY,
    session_key VARCHAR(255) NOT NULL,
    user_hash VARCHAR(64) NOT NULL,
    source_region VARCHAR(50),
    selected_node_id VARCHAR(100) REFERENCES gso_network_nodes(node_id),
    decision_score DECIMAL(5,2),
    decision_vector JSONB,
    decision_time_ms INTEGER,
    routing_mode VARCHAR(20),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE gso_region_isolations (
    region_code VARCHAR(50) PRIMARY KEY REFERENCES region_catalog(region_code),
    is_active BOOLEAN DEFAULT false,
    emergency_level INTEGER NOT NULL,
    reason TEXT,
    activated_at TIMESTAMPTZ,
    deactivated_at TIMESTAMPTZ
);

CREATE TABLE gso_emergency_incidents (
    incident_id VARCHAR(100) PRIMARY KEY,
    status VARCHAR(20) DEFAULT 'active',
    level INTEGER NOT NULL,
    region_code VARCHAR(50) REFERENCES region_catalog(region_code),
    reason TEXT,
    pc365_verified BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

CREATE TABLE gso_action_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    action_type VARCHAR(50) NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    region_code VARCHAR(50),
    detail JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE gso_degraded_tx_queue (
    tx_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    idempotency_key VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(20) DEFAULT 'pending', -- 'pending', 'completed', 'failed'
    payload_encrypted TEXT NOT NULL,
    payload_checksum VARCHAR(64) NOT NULL,
    metadata JSONB DEFAULT '{}',
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE gso_vault_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_key VARCHAR(255) NOT NULL,
    payload JSONB NOT NULL,
    payload_checksum VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE gso_session_routes (
    session_key VARCHAR(255) PRIMARY KEY,
    active_node_id VARCHAR(100) REFERENCES gso_network_nodes(node_id),
    metadata JSONB DEFAULT '{}',
    last_switch_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial region
INSERT INTO region_catalog (region_code, brand_config, locale_config)
VALUES ('AF-EAST', '{"primary_color": "#000000"}', '{"timezone": "Africa/Nairobi"}');

-- Seed a default Cloud Node
INSERT INTO gso_network_nodes (node_id, region_code, node_type, endpoint_url)
VALUES ('cloud-af-east-01', 'AF-EAST', 'cloud_region', 'https://af-east.pulsco.global');

CREATE INDEX idx_gso_routing_session ON gso_routing_decisions(session_key);
CREATE INDEX idx_gso_tx_queue_status ON gso_degraded_tx_queue(status, created_at);
CREATE INDEX idx_gso_vault_key ON gso_vault_documents(document_key);
"""

REVERSE_SQL_007_EDGE_GATEWAY = """
DROP TABLE IF EXISTS gso_session_routes;
DROP TABLE IF EXISTS gso_vault_documents;
DROP TABLE IF EXISTS gso_degraded_tx_queue;
DROP TABLE IF EXISTS gso_action_logs;
DROP TABLE IF EXISTS gso_emergency_incidents;
DROP TABLE IF EXISTS gso_region_isolations;
DROP TABLE IF EXISTS gso_routing_decisions;
DROP TABLE IF EXISTS gso_network_nodes;
DROP TABLE IF EXISTS region_catalog;

DROP INDEX IF EXISTS idx_geocoding_logs_provider;
DROP INDEX IF EXISTS idx_geocoding_logs_request_id;
DROP INDEX IF EXISTS idx_marketing_deliveries_region;
DROP INDEX IF EXISTS idx_marketing_deliveries_campaign;
DROP INDEX IF EXISTS idx_chatbot_logs_user_id;
DROP INDEX IF EXISTS idx_chatbot_logs_session_id;
DROP INDEX IF EXISTS idx_ai_program_runs_subsystem;
DROP INDEX IF EXISTS idx_ai_program_runs_program_id;
DROP INDEX IF EXISTS idx_matchmaking_events_region;
DROP INDEX IF EXISTS idx_matchmaking_events_match_id;
DROP INDEX IF EXISTS idx_edge_adapter_registry_capabilities;
DROP INDEX IF EXISTS idx_edge_adapter_registry_subsystem;
DROP INDEX IF EXISTS idx_edge_policy_snapshots_active_lookup;
DROP INDEX IF EXISTS idx_edge_policy_snapshots_subsystem_region;
DROP INDEX IF EXISTS idx_edge_anomalies_created_at;
DROP INDEX IF EXISTS idx_edge_anomalies_type_severity;
DROP INDEX IF EXISTS idx_edge_telemetry_created_at;
DROP INDEX IF EXISTS idx_edge_telemetry_subsystem;
DROP INDEX IF EXISTS idx_edge_telemetry_request_id;
DROP INDEX IF EXISTS idx_edge_audit_user_id;
DROP INDEX IF EXISTS idx_edge_audit_created_at;
DROP INDEX IF EXISTS idx_edge_audit_subsystem_decision;
DROP INDEX IF EXISTS idx_edge_audit_request_id;

DROP TABLE IF EXISTS edge_geocoding_logs;
DROP TABLE IF EXISTS edge_marketing_deliveries;
DROP TABLE IF EXISTS edge_chatbot_logs;
DROP TABLE IF EXISTS edge_ai_program_runs;
DROP TABLE IF EXISTS edge_matchmaking_events;
DROP TABLE IF EXISTS edge_adapter_registry;
DROP TABLE IF EXISTS edge_policy_snapshots;
DROP TABLE IF EXISTS edge_anomalies;
DROP TABLE IF EXISTS edge_telemetry;
DROP TABLE IF EXISTS edge_audit;
"""

SQL_006_MARP_OBSERVABILITY = """
-- MARP Observability Schema Migration
-- Implements monitoring, alerting, and metrics collection for planetary governance

-- Council Decisions table: Stores results of MARP arbitration
CREATE TABLE council_decisions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    status VARCHAR(50) NOT NULL, -- 'pending', 'approved', 'rejected'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Alerts table: Stores all system alerts and notifications
CREATE TABLE marp_alerts (
    id VARCHAR(255) PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL, -- 'slo_breach', 'anomaly', 'security', 'system'
    severity VARCHAR(20) NOT NULL, -- 'low', 'medium', 'high', 'critical'
    title VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    metric VARCHAR(255) NOT NULL,
    threshold_value JSONB,
    current_value JSONB,
    subsystem_name VARCHAR(100),
    acknowledged_at TIMESTAMPTZ,
    acknowledged_by VARCHAR(255),
    resolved_at TIMESTAMPTZ,
    resolved_by VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Metrics snapshots table: Stores periodic metrics snapshots
CREATE TABLE metrics_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    snapshot_type VARCHAR(50) NOT NULL, -- 'quorum_latency', 'firewall_actions', 'subsystem_health'
    snapshot_data JSONB NOT NULL,
    snapshot_period_start TIMESTAMPTZ NOT NULL,
    snapshot_period_end TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SLO tracking table: Tracks Service Level Objectives
CREATE TABLE slo_tracking (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slo_name VARCHAR(255) NOT NULL,
    slo_description TEXT,
    target_value DECIMAL(10,4) NOT NULL,
    current_value DECIMAL(10,4),
    status VARCHAR(20) NOT NULL, -- 'healthy', 'warning', 'breached'
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User protection status table: Tracks user protection levels
CREATE TABLE user_protection_status (
    user_id VARCHAR(255) PRIMARY KEY,
    protection_level VARCHAR(20) NOT NULL DEFAULT 'standard', -- 'standard', 'enhanced', 'maximum'
    active_rules JSONB NOT NULL DEFAULT '[]',
    risk_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    quarantine_status VARCHAR(20), -- 'active', 'cleared'
    last_assessment TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Governance snapshots table: Stores governance state snapshots
CREATE TABLE governance_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    snapshot_type VARCHAR(50) NOT NULL, -- 'full', 'incremental'
    snapshot_data JSONB NOT NULL,
    snapshot_hash VARCHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT false,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_marp_alerts_type_severity ON marp_alerts(alert_type, severity);
CREATE INDEX idx_marp_alerts_created_at ON marp_alerts(created_at DESC);
CREATE INDEX idx_marp_alerts_status ON marp_alerts(acknowledged_at, resolved_at);

CREATE INDEX idx_metrics_snapshots_type_period ON metrics_snapshots(snapshot_type, snapshot_period_start, snapshot_period_end);
CREATE INDEX idx_metrics_snapshots_created_at ON metrics_snapshots(created_at DESC);

CREATE INDEX idx_slo_tracking_name_status ON slo_tracking(slo_name, status);
CREATE INDEX idx_slo_tracking_updated ON slo_tracking(last_updated DESC);

CREATE INDEX idx_user_protection_level ON user_protection_status(protection_level);
CREATE INDEX idx_user_protection_risk ON user_protection_status(risk_score DESC);
CREATE INDEX idx_user_protection_assessment ON user_protection_status(last_assessment DESC);

CREATE INDEX idx_governance_snapshots_active ON governance_snapshots(is_active) WHERE is_active = true;
CREATE INDEX idx_governance_snapshots_created ON governance_snapshots(created_at DESC);

-- Insert default SLO definitions
INSERT INTO slo_tracking (slo_name, slo_description, target_value, status) VALUES
('snapshot_distribution', 'Governance snapshot distribution latency', 5.0, 'healthy'),
('policy_validation', 'Policy validation response time (p95)', 0.5, 'healthy'),
('audit_completeness', 'Audit log completeness percentage', 100.0, 'healthy'),
('signature_verification', 'Signature verification success rate', 100.0, 'healthy'),
('quorum_formation', 'Council quorum formation time', 30.0, 'healthy');

-- Insert default governance snapshot
INSERT INTO governance_snapshots (
    snapshot_type, snapshot_data, snapshot_hash, is_active, created_by
) VALUES (
    'initial',
    '{"councils": [], "policies": [], "firewall_rules": []}'::jsonb,
    'initial_snapshot_hash',
    true,
    'system'
);

-- Create function to update SLO status
CREATE OR REPLACE FUNCTION update_slo_status()
RETURNS void AS $$
DECLARE
    snapshot_age_seconds DECIMAL;
    quorum_avg_latency DECIMAL;
    sig_verification_rate DECIMAL;
BEGIN
    -- Update snapshot distribution SLO
    SELECT EXTRACT(EPOCH FROM (NOW() - MAX(created_at)))
    INTO snapshot_age_seconds
    FROM governance_snapshots WHERE is_active = true;

    UPDATE slo_tracking
    SET current_value = snapshot_age_seconds,
        status = CASE WHEN snapshot_age_seconds <= 5 THEN 'healthy' ELSE 'breached' END,
        last_updated = NOW()
    WHERE slo_name = 'snapshot_distribution';

    -- Update policy validation SLO
    SELECT AVG(EXTRACT(EPOCH FROM (updated_at - created_at)))
    INTO quorum_avg_latency
    FROM council_decisions
    WHERE status = 'approved' AND created_at >= NOW() - INTERVAL '1 hour';

    UPDATE slo_tracking
    SET current_value = COALESCE(quorum_avg_latency, 0),
        status = CASE WHEN COALESCE(quorum_avg_latency, 0) <= 0.5 THEN 'healthy' ELSE 'breached' END,
        last_updated = NOW()
    WHERE slo_name = 'policy_validation';


    -- Update audit completeness SLO
    UPDATE slo_tracking
    SET current_value = 100.0, -- Assume 100% for now
        status = 'healthy',
        last_updated = NOW()
    WHERE slo_name = 'audit_completeness';

END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update SLO status
CREATE OR REPLACE FUNCTION trigger_update_slo_status()
RETURNS trigger AS $$
BEGIN
    PERFORM update_slo_status();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers on relevant tables
-- The 'council_decisions' table is not defined in the provided SQL.
-- The trigger depending on it is commented out to prevent errors.
CREATE TRIGGER governance_snapshot_slo_trigger
    AFTER INSERT OR UPDATE ON governance_snapshots
    FOR EACH STATEMENT
    EXECUTE FUNCTION trigger_update_slo_status();

CREATE TRIGGER council_decision_slo_trigger
    AFTER INSERT OR UPDATE ON council_decisions
    FOR EACH STATEMENT
    EXECUTE FUNCTION trigger_update_slo_status();
"""

REVERSE_SQL_006_MARP_OBSERVABILITY = """
DROP TRIGGER IF EXISTS council_decision_slo_trigger ON council_decisions;
DROP TRIGGER IF EXISTS governance_snapshot_slo_trigger ON governance_snapshots;
DROP FUNCTION IF EXISTS trigger_update_slo_status();
DROP FUNCTION IF EXISTS update_slo_status();

DROP INDEX IF EXISTS idx_governance_snapshots_created;
DROP INDEX IF EXISTS idx_governance_snapshots_active;
DROP INDEX IF EXISTS idx_user_protection_assessment;
DROP INDEX IF EXISTS idx_user_protection_risk;
DROP INDEX IF EXISTS idx_user_protection_level;
DROP INDEX IF EXISTS idx_slo_tracking_updated;
DROP INDEX IF EXISTS idx_slo_tracking_name_status;
DROP INDEX IF EXISTS idx_metrics_snapshots_created_at;
DROP INDEX IF EXISTS idx_metrics_snapshots_type_period;
DROP INDEX IF EXISTS idx_marp_alerts_status;
DROP INDEX IF EXISTS idx_marp_alerts_created_at;
DROP INDEX IF EXISTS idx_marp_alerts_type_severity;

DROP TABLE IF EXISTS governance_snapshots;
DROP TABLE IF EXISTS council_decisions;
DROP TABLE IF EXISTS user_protection_status;
DROP TABLE IF EXISTS slo_tracking;
DROP TABLE IF EXISTS metrics_snapshots;
DROP TABLE IF EXISTS marp_alerts;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),  # Assuming 'billing' app has an initial migration
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL_007_EDGE_GATEWAY,
            reverse_sql=REVERSE_SQL_007_EDGE_GATEWAY,
            state_operations=[
                # Add dummy models here if you want Django to track these tables.
                # For raw SQL migrations, this is often omitted if Django models
                # are not directly interacting with these tables.
            ]
        ),
        migrations.RunSQL(
            sql=SQL_006_MARP_OBSERVABILITY,
            reverse_sql=REVERSE_SQL_006_MARP_OBSERVABILITY,
            state_operations=[
                # Add dummy models here if you want Django to track these tables.
            ]
        ),
    ]